import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import About from "../components/About";
import HomeImage from "../components/HomeImage";
import InfoSection from "../components/InfoSection";
import { infoOne, infoTwo } from "../components/InfoSection/data";



export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeImage id="home" />
      <InfoSection {...infoOne}/>
      <InfoSection {...infoTwo}/>
      <About/>
    </div>
  );
}
